### ISSUE TITLE
Los comandos con ! no funcionan desde IRC

### ISSUE THREAD

**Issue by peorth80** [sysarmy/bot.ai#5]
Usar el `!comando` desde IRC no lo procesa el bot de Discord, sino el viejo bot de IRC.

![image](https://github.com/user-attachments/assets/0edd0d9e-abde-44e9-a672-fa242217d190)

**Comment by maragunde** [comment]
Working on it. Fix probablemente salga esta semana

**Comment by pulpo** [comment]
No sé como abrigarme, el bot no me responde, vengo a poner presión y ofrecerme para las pruebas.

**Comment by edux** [comment]
El problema esta en que discord.py ignora por defecto todos los mensajes de los bots, solo procesa de usuarios reales. https://github.com/Rapptz/discord.py/issues/2238
https://www.reddit.com/r/discordbots/comments/v1bafy/discordpy_bot_run_other_bots_ctx_command/

```
new content:'!ping'
<Message id=x channel=<TextChannel id=x name='sysarmy🔥' position=13 nsfw=False news=False category_id=x> type=<MessageType.default: 0> author=<Member id=x
x name='bridgebot' global_name=None bot=True nick='bot' guild=<Guild id=x name='sysarmy' shard_id=0 chunked=True member_count=9073>> flags=<MessageFlags value=0>> !ping
``` ahi el bot=True rompe el command process. en esos links hay un par de workarounds, la alternativa sino es tener un procesador de comandos separados para el IRC que llame las funciones de comandos de discord directamente.
