### ISSUE TITLE
comandos desde el IRC toman el ! en cualquier posicion

### ISSUE THREAD

**Issue by edux** [sysarmy/bot.ai#7]
si mandas por irc "gracias !!!" lo toma como un comando, deberia solo tomar cuando inicia el mensaje.

**Comment by maragunde** [comment]
Le sacamos el msj que tira de "comando inexistente" y listo? Que te parece

**Comment by edux** [comment]
Hay que arreglar esta linea 
```            if '!' in message.content:```
https://github.com/sysarmy/bot.ai/blob/0967dfc0f9775fbc9d00526bf558f4762e54ec63/main.py#L354
Para que solo True si matchea que `<nbot> !` ( o como sea que viene del irc no recuerdo exactamente ahora)
